name: info_sat
description: Aplicación para obtener la información fiscal del contribuyente.

publish_to: "none"
version: 1.0.0+6

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1
  mobile_scanner: ^6.0.2

  sat_scraping:
    path: ../

  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
