name: info_sat
description: Aplicación para obtener la información fiscal del contribuyente.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^10.2.0
  qrscan: ^0.3.3

  sat_scraping:
    path: ../

  cupertino_icons: ^1.0.2
  share_plus: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
